# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateField(auto_created=True)),
                ('added_on', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='')),
                ('released_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lyricist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('bio', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=60)),
                ('released_on', models.DateField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Album')),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lyricist')),
            ],
        ),
    ]
