# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171031_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='added_on',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
