# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171031_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='meaning',
            field=models.TextField(default=' ', max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
