# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171114_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img',
            field=models.ImageField(upload_to=main.models.album_img),
        ),
    ]
