# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20171114_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='trend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='trend',
            field=models.IntegerField(default=0),
        ),
    ]
